install: gradle wrapper --gradle-version 4.2
language: groovy
jdk:
- oraclejdk8
sudo: false
dist: trusty
branches:
  only:
  - master
  - develop
  - FFTF
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - secure: O2wCRbwCgt6B81dptx3bng0FBllAfFMkNpqNv3Z6TL3LHl1EZJx9aW0xZy+YhX0ILbK3tmKJ+kqQU2EKS8LiuV9fH6CN0+5BkuK2qzcge0kUopvzVwDJw8+ltBAPqwA/ZKTLxCiCplzdRtXmLCfrZgw9icxD9ZNJkTMdM/1zC53xXXkrBv7zpQ5lEljSr5DgqkfG90eDxsMbXt7jlR9f1tsar1Q/ffdESeDcffwnwlLoN5ubYU9MUDRK+bLPrRkirsq/2LiQ/txzfEnvJ4kVY8gn7Avu69CXrFcomApRbIsgDQiMAwS79aSFDqtPb6mkzeMXyikXQvsiRJeslXlzi1M6EHr020erHADmUwIbM/kvhNhQPOZ2hdVSbXLRLKLedsHXXKKY2yHiOGg20l0rhdHiHQXhITNCsMgwoWYfdVXfW/Frk/9ozu8mpQyqAhcxWsfQp+Or8rBK5fE2+hohLof3mYeqG0sr2QAX+RMqH89ZOjZgybR6xYhUJzOvRUPWMII/D7XqJ8KZe4LsllPe7NOLLx1B7uIWlXsGeLlE+WZZyaZi8txE/b418xacKKcFriljky3ezifyPIv9DVyRo1g3Koi5kX8QSI68+KY1/m9Af85K9CcZjdqPgaOHz61Z2+xBx/zI+4qVy2zGIUNvc9D2bMgoB87/X6urZ2WeF5A=
  - secure: XADfHy+99HYoC4QHcWLEqq4jclGJQk1SrxjXoE+l7VsYn5i4zeTHqWEb1LWaGiAJm/Dew3IliaHXigfMoelSJ3jKh9RohK2b8BwuubZFZm4NjwF+VGh+b17z/TrQR6eHvXMdBYpPDgz5WjDDvoHtxVPsroET9cJKlHlanARlrWN8KyWedPzrJ5SwsC7MHM6Lu565BkuQPiCRV9ZkbnSI37EHHipF6gBU90cwBYbdEU+nnlstfSKi/Aooh7MR5Ypjg/EmAU2ShLuz0rCEGAIyw2R8+pGFF51SobYccKFji2z0TilCjbQYV8vgYbi1skgwDkymo0YFJiT63hsMSNv8v3pbD+sulR+NRearEyK5UoLPOdf/K0Fe4Cf2fSgb5eTJVVDPT9S0vTRYtClcKs80BMRWzY1zkJmY7IC4XhpXltOsolm5ENwIO9f4QdB/0nR5xzwhcpgFvPa2o+NE0DKB06CJrgwAsw5miv8DAzyt7iJKP5o8hSQNpwN4IJhcJDzKXZAzfxk7f/0HEa/kCrZgMiFZTIKrupXewoQ1KqtauZmLPEB65NVo17cURB+E0F9eX9p+BKNSEM/jPWNOqSBq0dciUdii6ToYcCoDo8Q9RTH2QzKarUqcQcQD5V+yGxsDFlxJwUJJ8KGP9T4iGvWZD201tVTD9QTf8SO1ERRirHk=
